-- Esquema de Usuarios: roles, cuentas y sesiones.

CREATE SCHEMA usuarios;

CREATE TABLE usuarios.roles (
  id_rol smallint PRIMARY KEY,
  nombre text NOT NULL UNIQUE
);

INSERT INTO usuarios.roles (id_rol, nombre) VALUES
  (1, 'CLIENTE'),
  (2, 'VENDEDOR'),
  (3, 'BODEGA'),
  (4, 'GERENTE'),
  (5, 'RRHH');

CREATE TABLE usuarios.usuarios (
  id_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL CHECK (btrim(nombre) <> ''),
  -- Se guarda en minúsculas para que la unicidad no dependa de cómo se escribió.
  email text NOT NULL UNIQUE CHECK (email = lower(btrim(email))),
  hash_contrasena text NOT NULL,
  id_rol smallint NOT NULL REFERENCES usuarios.roles,
  activo boolean NOT NULL DEFAULT true,
  creado_en timestamptz NOT NULL DEFAULT now()
);

-- Una fila por token de refresco emitido. Se guarda solo su hash, de modo que
-- una copia de la base no permita suplantar sesiones.
CREATE TABLE usuarios.sesiones (
  id_sesion bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_usuario integer NOT NULL REFERENCES usuarios.usuarios,
  hash_token_refresco text NOT NULL UNIQUE,
  expira_en timestamptz NOT NULL,
  revocada boolean NOT NULL DEFAULT false,
  creada_en timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX sesiones_por_usuario ON usuarios.sesiones (id_usuario) WHERE NOT revocada;
