-- Esquema de Inventario: catálogo, existencias por ubicación, reservas y movimientos.
--
-- Las columnas `clave` guardan el nombre sin mayúsculas ni tildes (lo calcula el
-- servicio). Su unicidad impide registrar "Metallica" y "metállica" como dos bandas.

CREATE SCHEMA inventario;

CREATE TABLE inventario.tallas (
  id_talla integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL CHECK (btrim(nombre) <> ''),
  clave text NOT NULL UNIQUE
);

CREATE TABLE inventario.colores (
  id_color integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL CHECK (btrim(nombre) <> ''),
  clave text NOT NULL UNIQUE
);

CREATE TABLE inventario.bandas (
  id_banda integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL CHECK (btrim(nombre) <> ''),
  clave text NOT NULL UNIQUE
);

CREATE TABLE inventario.categorias (
  id_categoria integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL CHECK (btrim(nombre) <> ''),
  clave text NOT NULL UNIQUE,
  -- Las categorías sin banda, como los pantalones, no muestran ese campo.
  usa_banda boolean NOT NULL DEFAULT true,
  -- Zona de la bodega: las letras del código de ubicación "B-<zona>-<posición>".
  zona text NOT NULL UNIQUE,
  -- Última posición entregada en la zona; la siguiente es correlativa.
  ultima_posicion integer NOT NULL DEFAULT 0 CHECK (ultima_posicion >= 0)
);

-- Tallas que admite cada categoría, en el orden en que se ofrecen.
CREATE TABLE inventario.categorias_tallas (
  id_categoria integer NOT NULL REFERENCES inventario.categorias,
  id_talla integer NOT NULL REFERENCES inventario.tallas,
  orden integer NOT NULL,
  PRIMARY KEY (id_categoria, id_talla)
);

CREATE TABLE inventario.productos (
  id_producto integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_categoria integer NOT NULL REFERENCES inventario.categorias,
  id_banda integer REFERENCES inventario.bandas,
  codigo_ubicacion text NOT NULL UNIQUE,
  nombre text NOT NULL CHECK (btrim(nombre) <> ''),
  clave text NOT NULL UNIQUE,
  descripcion text,
  imagen_url text,
  -- El precio y el costo los define el Gerente; un producto recién creado desde bodega aún no los tiene.
  precio integer CHECK (precio >= 0),
  costo_compra integer CHECK (costo_compra >= 0),
  peso_gramos integer CHECK (peso_gramos > 0),
  alto_cm integer CHECK (alto_cm > 0),
  ancho_cm integer CHECK (ancho_cm > 0),
  largo_cm integer CHECK (largo_cm > 0),
  activo boolean NOT NULL DEFAULT true
);

CREATE TABLE inventario.variantes (
  id_variante integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_producto integer NOT NULL REFERENCES inventario.productos,
  id_talla integer NOT NULL REFERENCES inventario.tallas,
  id_color integer NOT NULL REFERENCES inventario.colores,
  sku text NOT NULL UNIQUE,
  codigo text NOT NULL UNIQUE,
  activo boolean NOT NULL DEFAULT true,
  UNIQUE (id_producto, id_talla, id_color)
);

CREATE TABLE inventario.ubicaciones (
  id_ubicacion smallint PRIMARY KEY,
  nombre text NOT NULL UNIQUE
);

INSERT INTO inventario.ubicaciones (id_ubicacion, nombre) VALUES
  (1, 'BODEGA'),
  (2, 'SALA_VENTAS');

-- Saldo por variante y ubicación. Debe coincidir con la suma de los movimientos; se
-- mantiene como dato para poder bloquear y validar el stock de forma atómica.
CREATE TABLE inventario.existencias (
  id_variante integer NOT NULL REFERENCES inventario.variantes,
  id_ubicacion smallint NOT NULL REFERENCES inventario.ubicaciones,
  cantidad integer NOT NULL DEFAULT 0 CHECK (cantidad >= 0),
  PRIMARY KEY (id_variante, id_ubicacion)
);

-- Unidades comprometidas en compras del e-commerce que aún no se despachan.
CREATE TABLE inventario.reservas (
  id_reserva bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_venta bigint NOT NULL,
  id_variante integer NOT NULL REFERENCES inventario.variantes,
  cantidad integer NOT NULL CHECK (cantidad > 0),
  estado text NOT NULL CHECK (estado IN ('ACTIVA', 'CONFIRMADA', 'LIBERADA', 'DESPACHADA')),
  -- Solo las reservas ACTIVA vencen; una CONFIRMADA queda firme hasta el despacho.
  expira_en timestamptz
);

CREATE INDEX reservas_vigentes ON inventario.reservas (id_variante) WHERE estado IN ('ACTIVA', 'CONFIRMADA');

CREATE TABLE inventario.tipos_movimiento (
  id_tipo smallint PRIMARY KEY,
  codigo text NOT NULL UNIQUE
);

INSERT INTO inventario.tipos_movimiento (id_tipo, codigo) VALUES
  (1, 'INGRESO'),
  (2, 'VENTA'),
  (3, 'DEVOLUCION'),
  (4, 'DESPACHO'),
  (5, 'MERMA'),
  (6, 'TRASPASO'),
  (7, 'AJUSTE');

CREATE TABLE inventario.tipos_merma (
  id_tipo_merma smallint PRIMARY KEY,
  codigo text NOT NULL UNIQUE
);

INSERT INTO inventario.tipos_merma (id_tipo_merma, codigo) VALUES
  (1, 'DANADO'),
  (2, 'MUESTRA'),
  (3, 'CAMBIO');

-- Una fila por operación confirmada. La clave la genera el cliente: reenviar la
-- misma no repite la operación, se responde lo que ya quedó registrado.
CREATE TABLE inventario.operaciones (
  clave_idempotencia text PRIMARY KEY,
  tipo text NOT NULL,
  id_usuario integer NOT NULL REFERENCES usuarios.usuarios,
  creada_en timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE inventario.movimientos (
  id_movimiento bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_variante integer NOT NULL REFERENCES inventario.variantes,
  id_ubicacion smallint NOT NULL REFERENCES inventario.ubicaciones,
  id_ubicacion_destino smallint REFERENCES inventario.ubicaciones,
  id_tipo smallint NOT NULL REFERENCES inventario.tipos_movimiento,
  id_tipo_merma smallint REFERENCES inventario.tipos_merma,
  -- Unidades movidas; en un ajuste es la diferencia aplicada y puede ser negativa.
  cantidad integer NOT NULL,
  fecha timestamptz NOT NULL DEFAULT now(),
  id_usuario integer NOT NULL REFERENCES usuarios.usuarios,
  motivo text NOT NULL CHECK (btrim(motivo) <> ''),
  id_venta bigint,
  -- Un ingreso de varias prendas comparte una misma clave entre sus movimientos.
  clave_idempotencia text REFERENCES inventario.operaciones
);

CREATE INDEX movimientos_por_variante ON inventario.movimientos (id_variante, fecha DESC);
CREATE INDEX movimientos_por_operacion ON inventario.movimientos (clave_idempotencia);

CREATE TABLE inventario.conteos (
  id_conteo bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_variante integer NOT NULL REFERENCES inventario.variantes,
  id_ubicacion smallint NOT NULL REFERENCES inventario.ubicaciones,
  cantidad_sistema integer NOT NULL,
  cantidad_contada integer NOT NULL CHECK (cantidad_contada >= 0),
  id_usuario integer NOT NULL REFERENCES usuarios.usuarios,
  fecha timestamptz NOT NULL DEFAULT now(),
  etapa text NOT NULL DEFAULT 'AJUSTE'
);

-- Tiempo que toma ubicar una prenda. `fin` queda vacío si la búsqueda se canceló.
CREATE TABLE inventario.busquedas (
  id_busqueda bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_variante integer NOT NULL REFERENCES inventario.variantes,
  id_usuario integer NOT NULL REFERENCES usuarios.usuarios,
  inicio timestamptz NOT NULL DEFAULT now(),
  fin timestamptz
);
