-- Esquema de Ventas. Por ahora solo lo necesario para que un pedido del e-commerce
-- tenga su venta y sus líneas; el resto de las tablas del diseño (costos, visitas,
-- parámetros financieros) se agrega junto con el módulo de ventas.

CREATE SCHEMA ventas;

CREATE TABLE ventas.estados_venta (
  id_estado smallint PRIMARY KEY,
  codigo text NOT NULL UNIQUE
);

INSERT INTO ventas.estados_venta (id_estado, codigo) VALUES
  (1, 'PENDIENTE_PAGO'),
  (2, 'PAGADA'),
  (3, 'RECHAZADA'),
  (4, 'EXPIRADA'),
  (5, 'REVERSADA');

CREATE TABLE ventas.ventas (
  id_venta bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  canal text NOT NULL CHECK (canal IN ('POS', 'ECOMMERCE')),
  id_vendedor integer REFERENCES usuarios.usuarios,
  id_cliente integer REFERENCES usuarios.usuarios,
  id_estado smallint NOT NULL REFERENCES ventas.estados_venta,
  fecha timestamptz NOT NULL DEFAULT now(),
  -- Monto cobrado en pesos, con el flete incluido.
  total integer NOT NULL CHECK (total >= 0),
  clave_idempotencia text NOT NULL UNIQUE,
  -- Una venta POS la registra un vendedor; una del e-commerce pertenece a un cliente.
  CHECK ((canal = 'POS' AND id_vendedor IS NOT NULL) OR (canal = 'ECOMMERCE' AND id_cliente IS NOT NULL))
);

CREATE TABLE ventas.detalle_venta (
  id_detalle bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_venta bigint NOT NULL REFERENCES ventas.ventas,
  id_variante integer NOT NULL REFERENCES inventario.variantes,
  cantidad integer NOT NULL CHECK (cantidad > 0),
  -- Valores al momento de vender: no cambian si después cambia el precio del producto.
  precio_unitario integer NOT NULL CHECK (precio_unitario >= 0),
  costo_unitario integer CHECK (costo_unitario >= 0),
  subtotal integer GENERATED ALWAYS AS (cantidad * precio_unitario) STORED
);

CREATE INDEX detalle_por_venta ON ventas.detalle_venta (id_venta);
