-- Esquema de Logística: destinos y pedidos del e-commerce.

CREATE SCHEMA logistica;

CREATE TABLE logistica.regiones (
  id_region smallint PRIMARY KEY,
  nombre text NOT NULL UNIQUE
);

INSERT INTO logistica.regiones (id_region, nombre) VALUES
  (1, 'Arica y Parinacota'),
  (2, 'Tarapacá'),
  (3, 'Antofagasta'),
  (4, 'Atacama'),
  (5, 'Coquimbo'),
  (6, 'Valparaíso'),
  (7, 'Región Metropolitana'),
  (8, 'O’Higgins'),
  (9, 'Maule'),
  (10, 'Ñuble'),
  (11, 'Biobío'),
  (12, 'La Araucanía'),
  (13, 'Los Ríos'),
  (14, 'Los Lagos'),
  (15, 'Aysén'),
  (16, 'Magallanes');

CREATE TABLE logistica.comunas (
  id_comuna integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_region smallint NOT NULL REFERENCES logistica.regiones,
  nombre text NOT NULL,
  codigo_starken text,
  -- Zona tarifaria de respaldo cuando Starken no responde.
  zona text NOT NULL CHECK (zona IN ('SANTIAGO', 'REGIONES')),
  UNIQUE (id_region, nombre)
);

CREATE TABLE logistica.estados_pedido (
  id_estado smallint PRIMARY KEY,
  codigo text NOT NULL UNIQUE
);

INSERT INTO logistica.estados_pedido (id_estado, codigo) VALUES
  (1, 'PAGADO'),
  (2, 'EN_PREPARACION'),
  (3, 'DESPACHO_PENDIENTE'),
  (4, 'DESPACHADO'),
  (5, 'ENTREGADO'),
  (6, 'ATENCION_MANUAL');

CREATE TABLE logistica.pedidos (
  id_pedido bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Un pedido por venta.
  id_venta bigint NOT NULL UNIQUE REFERENCES ventas.ventas,
  id_estado smallint NOT NULL REFERENCES logistica.estados_pedido,
  id_comuna integer NOT NULL REFERENCES logistica.comunas,
  direccion text NOT NULL,
  destinatario text NOT NULL,
  telefono text,
  tracking_starken text,
  flete_cobrado integer NOT NULL DEFAULT 0 CHECK (flete_cobrado >= 0),
  costo_despacho integer CHECK (costo_despacho >= 0),
  pagado_en timestamptz NOT NULL,
  despachado_en timestamptz,
  entregado_en timestamptz
);

CREATE INDEX pedidos_por_estado ON logistica.pedidos (id_estado);

CREATE TABLE logistica.historial_pedido (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_pedido bigint NOT NULL REFERENCES logistica.pedidos,
  id_estado smallint NOT NULL REFERENCES logistica.estados_pedido,
  id_usuario integer REFERENCES usuarios.usuarios,
  fecha timestamptz NOT NULL DEFAULT now()
);
